CREATE TABLE [Master].Employees (
	ManagerID INT IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastNameName VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	DateOfBirth DATE NOT NULL,
	CONSTRAINT PK_MasterEmployeesManagerID PRIMARY KEY(ManagerID)
);